# Generated by Django 4.1.6 on 2023-03-06 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eab', '0004_profile_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parametre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appname', models.CharField(max_length=100)),
                ('appeditor', models.CharField(max_length=100)),
                ('phone', models.TextField()),
                ('email', models.TextField()),
                ('version', models.TextField()),
                ('devise', models.TextField()),
                ('theme', models.TextField(default='Primary')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('width_logo', models.TextField()),
                ('height_logo', models.TextField()),
            ],
        ),
    ]
