# Generated by Django 4.1.6 on 2023-03-06 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eab', '0005_parametre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.TextField()),
                ('message', models.TextField()),
                ('datecontact', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
