# Generated by Django 4.1.6 on 2023-03-07 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eab', '0008_alter_parametre_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='statut',
            field=models.IntegerField(null=True),
        ),
    ]
