# Generated by Django 4.1.6 on 2023-03-08 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eab', '0011_etablissement_formation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('posteoccupe', models.CharField(max_length=200)),
                ('projet_mission', models.TextField()),
            ],
        ),
    ]
