# Generated by Django 4.1.6 on 2023-03-08 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eab', '0014_parcours'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcours',
            name='entreprise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eab.entreprise'),
        ),
        migrations.AlterField(
            model_name='parcours',
            name='etablissement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eab.etablissement'),
        ),
        migrations.AlterField(
            model_name='parcours',
            name='formation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eab.formation'),
        ),
        migrations.AlterField(
            model_name='parcours',
            name='matiere',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eab.matiere'),
        ),
    ]
