# Generated by Django 4.1.6 on 2023-03-08 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eab', '0015_parcours_entreprise_alter_parcours_etablissement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcours',
            name='statut',
            field=models.CharField(choices=[('Etudiant', 'Etudiant'), ('Travailleur', 'Travailleur(se)')], max_length=200, null=True),
        ),
    ]
