# Generated by Django 4.1.6 on 2023-03-09 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eab', '0017_framework_langage_logiciel_modelisation_outils_sgbd_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_comp', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Framework',
        ),
        migrations.DeleteModel(
            name='Langage',
        ),
        migrations.DeleteModel(
            name='Logiciel',
        ),
        migrations.DeleteModel(
            name='Modelisation',
        ),
        migrations.DeleteModel(
            name='Outils',
        ),
        migrations.DeleteModel(
            name='SGBD',
        ),
        migrations.DeleteModel(
            name='Systeme',
        ),
        migrations.DeleteModel(
            name='Technologie',
        ),
    ]
