# Generated by Django 4.1.6 on 2023-03-09 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eab', '0018_competence_delete_framework_delete_langage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competence',
            name='type_comp',
            field=models.CharField(choices=[('Bureautique', 'Bureautique'), ('Système', 'Systeme'), ('Logiciel', 'Logiciel'), ('Langage', 'Langage'), ('Framework', 'Framework'), ('SGBD', 'SGBD'), ('Outil et Environnement', 'Outil et Environnement'), ('Modélisation', 'Modélisation')], max_length=100),
        ),
    ]
