# Generated by Django 4.1.6 on 2023-03-09 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eab', '0019_alter_competence_type_comp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competence',
            name='type_comp',
            field=models.CharField(choices=[('Bureautique', 'Bureautique'), ("Système d'exploitation", "Système d'exploitation"), ('Logiciel', 'Logiciel'), ('Langage de programmation', 'Langage de programmation'), ('Framework', 'Framework'), ('Système de Gestion de Base de Données', 'Système de Gestion de Base de Données'), ('Outil et Environnement', 'Outil et Environnement'), ('Modélisation', 'Modélisation')], max_length=100),
        ),
    ]
