# Generated by Django 4.1.6 on 2023-03-10 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eab', '0020_alter_competence_type_comp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcours',
            name='composant',
        ),
        migrations.RemoveField(
            model_name='parcours',
            name='entreprise',
        ),
        migrations.RemoveField(
            model_name='parcours',
            name='sous_composant',
        ),
    ]
