# Generated by Django 4.1.6 on 2023-03-10 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eab', '0023_competence_user_entreprise_user_etablissement_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entreprise',
            name='posteoccupe',
        ),
        migrations.RemoveField(
            model_name='entreprise',
            name='projet_mission',
        ),
        migrations.AlterField(
            model_name='experience',
            name='date_debut',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='date_fin',
            field=models.DateField(blank=True),
        ),
    ]
