# Generated by Django 4.1.6 on 2023-03-10 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eab', '0025_competence_comment_alter_competence_type_comp'),
    ]

    operations = [
        migrations.AddField(
            model_name='matiere',
            name='status',
            field=models.IntegerField(null=True),
        ),
    ]
