# Generated by Django 4.1.6 on 2023-03-11 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eab', '0027_competence_status_experience_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matiere',
            name='status',
        ),
        migrations.AddField(
            model_name='parcours',
            name='status',
            field=models.IntegerField(null=True),
        ),
    ]
