# Generated by Django 4.1.6 on 2023-03-11 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eab', '0029_alter_etablissement_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreprise',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='formation',
            name='intitule',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='matiere',
            name='libelle',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
