# Generated by Django 4.1.6 on 2023-03-11 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eab', '0031_alter_entreprise_name_alter_formation_intitule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competence',
            name='status',
            field=models.BooleanField(null=True),
        ),
    ]
