# Generated by Django 4.1.6 on 2023-03-11 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eab', '0032_alter_competence_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='status',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='parcours',
            name='status',
            field=models.BooleanField(null=True),
        ),
    ]
