# Generated by Django 4.1.6 on 2023-03-12 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eab', '0033_alter_experience_status_alter_parcours_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='codes',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
