# Generated by Django 4.1.6 on 2023-03-14 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eab', '0034_contact_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='status',
            field=models.IntegerField(null=True),
        ),
    ]
