# Generated by Django 4.1.6 on 2023-03-17 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eab', '0037_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='composant',
        ),
        migrations.RemoveField(
            model_name='question',
            name='discipline',
        ),
        migrations.RemoveField(
            model_name='question',
            name='user',
        ),
        migrations.DeleteModel(
            name='Composant',
        ),
        migrations.DeleteModel(
            name='Discipline',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
