# Generated by Django 4.1.6 on 2023-03-21 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eab', '0038_remove_question_composant_remove_question_discipline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='parametre',
            name='theme',
            field=models.CharField(choices=[('primary', 'primary'), ('info', 'Info'), ('success', 'success'), ('danger', 'danger'), ('secondary', 'secondary'), ('dark', 'dark')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
