# Generated by Django 4.1.6 on 2023-03-21 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eab', '0039_alter_contact_message_alter_parametre_theme_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametre',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
        migrations.AlterField(
            model_name='parametre',
            name='theme',
            field=models.CharField(choices=[('primary', 'primary'), ('info', 'info'), ('success', 'success'), ('danger', 'danger'), ('secondary', 'secondary'), ('dark', 'dark')], max_length=200, null=True),
        ),
    ]
