# Generated by Django 4.1.6 on 2023-03-21 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eab', '0040_alter_parametre_logo_alter_parametre_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametre',
            name='appeditor',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='parametre',
            name='devise',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='parametre',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='parametre',
            name='height_logo',
            field=models.TextField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='parametre',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='parametre',
            name='phone',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='parametre',
            name='version',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='parametre',
            name='width_logo',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
