# Generated by Django 4.1.6 on 2023-03-21 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eab', '0042_alter_parametre_logo_alter_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
