# Generated by Django 4.1.6 on 2023-04-07 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eab', '0045_competence_statusan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competence',
            name='statusan',
            field=models.CharField(default='Non', max_length=50, null=True),
        ),
    ]
