# Generated by Django 4.1.6 on 2023-04-07 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eab', '0046_alter_competence_statusan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competence',
            name='statusan',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
