# Generated by Django 4.1.6 on 2023-04-07 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eab', '0047_alter_competence_statusan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competence',
            name='statusan',
        ),
        migrations.AddField(
            model_name='parcours',
            name='statusan',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
