# Generated by Django 4.1.6 on 2023-04-07 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eab', '0048_remove_competence_statusan_parcours_statusan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcours',
            name='statusan',
            field=models.CharField(default='Non', max_length=50, null=True),
        ),
    ]
