# Generated by Django 4.1.6 on 2023-04-07 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eab', '0049_alter_parcours_statusan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcours',
            name='matiere',
        ),
    ]
