# Generated by Django 4.1.6 on 2023-04-07 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eab', '0050_remove_parcours_matiere'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Matiere',
        ),
    ]
