# Generated by Django 4.1.6 on 2023-04-08 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eab', '0051_delete_matiere'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='projet_mission',
            field=models.CharField(choices=[('Projet', 'Projet'), ('Mission', 'Mission')], max_length=100, null=True),
        ),
    ]
