# Generated by Django 4.1.6 on 2023-04-08 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eab', '0052_experience_title_alter_experience_projet_mission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
