# Generated by Django 4.1.6 on 2023-04-24 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eab', '0054_alter_parcours_niveau'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='statutdel',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
