# Generated by Django 4.1.6 on 2023-04-06 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0005_likes_likeanswer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Panier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cquantite', models.TextField(max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_created=True)),
                ('file', models.FileField(upload_to='upload')),
                ('title', models.CharField(max_length=100, null=True)),
                ('niveau', models.CharField(choices=[('Bac + 1', 'Bac + 1'), ('Bac + 2', 'Bac + 2'), ('Bac + 3', 'Bac + 3'), ('Bac + 4', 'Bac + 4'), ('Bac + 5', 'Bac + 5'), ('Bac + 6', 'Bac + 6'), ('Bac + 7', 'Bac + 7')], max_length=200, null=True)),
                ('comment', models.CharField(max_length=500, null=True)),
                ('type', models.CharField(choices=[('Gratuit', 'Gratuit'), ('Payant', 'Payant')], max_length=100, null=True)),
                ('price', models.IntegerField(default=0, null=True)),
                ('status', models.CharField(choices=[('Traitement en cours', 'Traitement en cours'), ('Cours publié', 'Cours publié'), ('Cours non retenu', 'Cours non retenu')], default='Traitement en cours', max_length=100, null=True)),
                ('etat', models.BooleanField(default=False, null=True)),
                ('content', models.TextField(null=True)),
                ('composant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.composant')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.discipline')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ucours', models.TextField(max_length=500, null=True)),
                ('total', models.IntegerField()),
                ('datecommande', models.DateField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
