# Generated by Django 4.1.6 on 2023-05-06 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_cours_st_alter_cours_niveau'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='statusachat',
            field=models.BooleanField(default=False),
        ),
    ]
