# Generated by Django 4.1.6 on 2023-05-17 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0003_commande_statusachat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cours',
            name='etat',
        ),
    ]
