# Generated by Django 4.1.6 on 2023-03-20 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='status',
            field=models.IntegerField(null=True),
        ),
    ]
